title: Ideation & Prototyping
description: Process documentation for weekly ideation and prototyping projects.
url: "https://bulahe.github.io"
baseurl: "/Ideation-prototyping-Process-Documentation"
theme: jekyll-theme-primer
plugins:
  - jekyll-readme-index
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - scripts
  - PREVIEW.md
  - UPLOAD.md
  - 50ways/assets/source
  - endangered-animal/assets/source
